/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import User.InventoryEmp;
import User.MarketingEmp;
import User.SalesEmp;
import java.awt.Color;
import javax.swing.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import Database.*;
import static Database.UDB.isUserIdUnique;
import static Database.UDB.isUserNameUnique;
import User.User;
/**
 *
 * @author shehab
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin(User u) {
        initComponents();
        
        //Add employee to table
            try{
            ArrayList<User> users = UDB.search("*");
            DefaultTableModel Etb = (DefaultTableModel) employeeTable.getModel();
                for(int i =1;i<users.size();i++){
                    String user[]={
                        String.valueOf(users.get(i).getId()) ,
                        users.get(i).getName() ,
                        users.get(i).getUserName() ,
                        users.get(i).getPassword() ,
                        users.get(i).getType()
                    };
                    Etb.addRow(user);
                }

            }catch(Exception error){
                    System.out.println(error.getLocalizedMessage());
            }
            
        //Set Admin data in Manage admin account page and set Welcome page
        try{
        ArrayList<User> adminAccount = UDB.search("id = 1");
        welcomeLabel.setText("Welcome, "+adminAccount.get(0).getName());
        currentAdminName.setText(adminAccount.get(0).getName());
        currentAdminPass.setText(adminAccount.get(0).getPassword());
        currentAdminUserName.setText(adminAccount.get(0).getUserName());
        updateNameTextBox.setText(currentAdminName.getText());
        updatePassTextBox.setText(currentAdminPass.getText());
        updateUserNameTextBox.setText(currentAdminUserName.getText());
            
        }catch(Exception error){
                    System.out.println(error.getLocalizedMessage());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        The_Main_Panel = new javax.swing.JPanel();
        Side_Bar = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Manage_admin = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        currentAdminPass = new javax.swing.JLabel();
        currentAdminPassLabel = new javax.swing.JLabel();
        currentAdminUserNameLabel = new javax.swing.JLabel();
        currentAdminName = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        Update_Account = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        updateUserNameTextBox = new javax.swing.JTextField();
        updatePassTextBox = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        updateNameTextBox = new javax.swing.JTextField();
        currentAdminNameLabel = new javax.swing.JLabel();
        currentAdminUserName = new javax.swing.JLabel();
        Mnagae_employee = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        deleteSelectedEmployee = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        EId = new javax.swing.JTextField();
        Epass = new javax.swing.JTextField();
        Ename = new javax.swing.JTextField();
        Add_Employee = new javax.swing.JButton();
        addType = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        userNameTextBox = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Eid = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        EnameU = new javax.swing.JTextField();
        EpassU = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Update_employee = new javax.swing.JButton();
        updateComboBox = new javax.swing.JComboBox<>();
        userNameTextBoxUpdate = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        The_Main_Panel.setBackground(java.awt.Color.white);
        The_Main_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Side_Bar.setBackground(new java.awt.Color(255, 241, 226));

        jButton1.setBackground(new java.awt.Color(255, 115, 29));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("Home");
        jButton1.setBorderPainted(false);
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton1FocusLost(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 115, 29));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setText("Manage Account");
        jButton2.setMaximumSize(new java.awt.Dimension(84, 26));
        jButton2.setMinimumSize(new java.awt.Dimension(84, 26));
        jButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton2MouseMoved(evt);
            }
        });
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 115, 29));
        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jButton4.setForeground(java.awt.Color.white);
        jButton4.setText("Manage Employees");
        jButton4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton4MouseMoved(evt);
            }
        });
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 115, 29));
        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jButton5.setForeground(java.awt.Color.white);
        jButton5.setText("Logout");
        jButton5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton5MouseMoved(evt);
            }
        });
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Side_BarLayout = new javax.swing.GroupLayout(Side_Bar);
        Side_Bar.setLayout(Side_BarLayout);
        Side_BarLayout.setHorizontalGroup(
            Side_BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Side_BarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Side_BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Side_BarLayout.createSequentialGroup()
                        .addGroup(Side_BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Side_BarLayout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11))))
        );
        Side_BarLayout.setVerticalGroup(
            Side_BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Side_BarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 546, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        The_Main_Panel.add(Side_Bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 870));

        jTabbedPane1.setBackground(java.awt.Color.white);
        jTabbedPane1.setForeground(new java.awt.Color(5, 58, 102));
        jTabbedPane1.setDoubleBuffered(true);

        Home.setBackground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(5, 58, 102));
        jLabel1.setText("ADMIN");

        jPanel4.setBackground(new java.awt.Color(255, 115, 29));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/market/imgs/adminLogo.png"))); // NOI18N

        welcomeLabel.setBackground(new java.awt.Color(0, 0, 0));
        welcomeLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 115, 29));
        welcomeLabel.setText(" ");

        jLabel6.setPreferredSize(new java.awt.Dimension(250, 250));

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addGap(0, 497, Short.MAX_VALUE)
                .addComponent(welcomeLabel)
                .addGap(335, 335, 335))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addComponent(welcomeLabel)
                .addContainerGap(491, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", Home);

        Manage_admin.setBackground(java.awt.Color.white);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(5, 58, 102));
        jLabel4.setText("Manage Admin Account");

        currentAdminPass.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        currentAdminPass.setForeground(new java.awt.Color(5, 58, 102));

        currentAdminPassLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        currentAdminPassLabel.setForeground(new java.awt.Color(255, 115, 29));
        currentAdminPassLabel.setText("Current Password   :");

        currentAdminUserNameLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        currentAdminUserNameLabel.setForeground(new java.awt.Color(255, 115, 29));
        currentAdminUserNameLabel.setText("Current User Name :");

        currentAdminName.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        currentAdminName.setForeground(new java.awt.Color(5, 58, 102));

        jPanel8.setBackground(new java.awt.Color(255, 115, 29));
        jPanel8.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        Update_Account.setBackground(java.awt.Color.white);
        Update_Account.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Update_Account.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(5, 58, 102));
        jLabel12.setText("Update Account");
        Update_Account.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 21, -1, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 115, 29));
        jLabel13.setText("User Name: ");
        Update_Account.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 32));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 115, 29));
        jLabel14.setText("Password: ");
        Update_Account.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 32));

        updateUserNameTextBox.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        updateUserNameTextBox.setForeground(new java.awt.Color(5, 58, 102));
        updateUserNameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserNameTextBoxActionPerformed(evt);
            }
        });
        Update_Account.add(updateUserNameTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 95, 34));

        updatePassTextBox.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        updatePassTextBox.setForeground(new java.awt.Color(5, 58, 102));
        updatePassTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePassTextBoxActionPerformed(evt);
            }
        });
        Update_Account.add(updatePassTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 95, 35));

        jButton3.setBackground(new java.awt.Color(255, 115, 29));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jButton3.setForeground(java.awt.Color.white);
        jButton3.setText("Update");
        jButton3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton3MouseMoved(evt);
            }
        });
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Update_Account.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 186, 35));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 115, 29));
        jLabel27.setText("Name:");
        Update_Account.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 32));

        updateNameTextBox.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        updateNameTextBox.setForeground(new java.awt.Color(5, 58, 102));
        updateNameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateNameTextBoxActionPerformed(evt);
            }
        });
        Update_Account.add(updateNameTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 95, 34));

        currentAdminNameLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        currentAdminNameLabel.setForeground(new java.awt.Color(255, 115, 29));
        currentAdminNameLabel.setText("Current Name :");

        currentAdminUserName.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        currentAdminUserName.setForeground(new java.awt.Color(5, 58, 102));

        javax.swing.GroupLayout Manage_adminLayout = new javax.swing.GroupLayout(Manage_admin);
        Manage_admin.setLayout(Manage_adminLayout);
        Manage_adminLayout.setHorizontalGroup(
            Manage_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Manage_adminLayout.createSequentialGroup()
                .addGroup(Manage_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Manage_adminLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(Manage_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Manage_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(currentAdminUserNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(currentAdminPassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(currentAdminNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Manage_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentAdminPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currentAdminUserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currentAdminName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Manage_adminLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(Update_Account, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Manage_adminLayout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addGroup(Manage_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(183, 183, 183))
        );
        Manage_adminLayout.setVerticalGroup(
            Manage_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Manage_adminLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(Manage_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(currentAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentAdminNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(Manage_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentAdminUserNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentAdminUserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(Manage_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentAdminPassLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentAdminPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(Update_Account, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        jTabbedPane1.addTab("Manage Admin Account", Manage_admin);

        Mnagae_employee.setBackground(java.awt.Color.white);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 115, 29));
        jLabel5.setText("Current Employees");

        jPanel7.setBackground(new java.awt.Color(255, 115, 29));
        jPanel7.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(5, 58, 102));
        jLabel11.setText("Manage Employees");

        deleteSelectedEmployee.setBackground(new java.awt.Color(255, 115, 29));
        deleteSelectedEmployee.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        deleteSelectedEmployee.setForeground(java.awt.Color.white);
        deleteSelectedEmployee.setText("Delete Employee");
        deleteSelectedEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSelectedEmployeeActionPerformed(evt);
            }
        });

        employeeTable.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        employeeTable.setForeground(new java.awt.Color(5, 58, 102));
        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "User name", "Password", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employeeTable.setAutoscrolls(false);
        employeeTable.setGridColor(java.awt.Color.black);
        employeeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(employeeTable);
        if (employeeTable.getColumnModel().getColumnCount() > 0) {
            employeeTable.getColumnModel().getColumn(0).setResizable(false);
            employeeTable.getColumnModel().getColumn(1).setResizable(false);
            employeeTable.getColumnModel().getColumn(2).setResizable(false);
            employeeTable.getColumnModel().getColumn(3).setResizable(false);
            employeeTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(5, 58, 102));
        jLabel15.setText("Add Employee");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 115, 29));
        jLabel17.setText("Id:");

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 115, 29));
        jLabel18.setText("Password:");

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 115, 29));
        jLabel19.setText("Name:");

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 115, 29));
        jLabel20.setText("Type:");

        EId.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        EId.setForeground(new java.awt.Color(5, 58, 102));
        EId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EIdActionPerformed(evt);
            }
        });

        Epass.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Epass.setForeground(new java.awt.Color(5, 58, 102));

        Ename.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Ename.setForeground(new java.awt.Color(5, 58, 102));

        Add_Employee.setBackground(new java.awt.Color(255, 115, 29));
        Add_Employee.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        Add_Employee.setForeground(java.awt.Color.white);
        Add_Employee.setText("Add");
        Add_Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_EmployeeActionPerformed(evt);
            }
        });

        addType.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        addType.setForeground(new java.awt.Color(5, 58, 102));
        addType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sales", "inventory", "marketing" }));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 115, 29));
        jLabel25.setText("User name");

        userNameTextBox.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        userNameTextBox.setForeground(new java.awt.Color(5, 58, 102));
        userNameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(jLabel15))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EId, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Ename, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel20))
                                    .addGap(56, 56, 56)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Epass)
                                        .addComponent(addType, 0, 95, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(userNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(Add_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ename, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Epass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Add_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(5, 58, 102));
        jLabel16.setText("Update Employee");

        Eid.setEditable(false);
        Eid.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Eid.setForeground(new java.awt.Color(5, 58, 102));
        Eid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EidActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 115, 29));
        jLabel21.setText("Id:");

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 115, 29));
        jLabel22.setText("Name:");

        EnameU.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        EnameU.setForeground(new java.awt.Color(5, 58, 102));

        EpassU.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        EpassU.setForeground(new java.awt.Color(5, 58, 102));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 115, 29));
        jLabel23.setText("Password:");

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 115, 29));
        jLabel24.setText("Type:");

        Update_employee.setBackground(new java.awt.Color(255, 115, 29));
        Update_employee.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        Update_employee.setForeground(java.awt.Color.white);
        Update_employee.setText("Update");
        Update_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_employeeActionPerformed(evt);
            }
        });

        updateComboBox.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        updateComboBox.setForeground(new java.awt.Color(5, 58, 102));
        updateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sales", "inventory", "marketing" }));

        userNameTextBoxUpdate.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        userNameTextBoxUpdate.setForeground(new java.awt.Color(5, 58, 102));

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 115, 29));
        jLabel26.setText("User name:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EpassU, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EnameU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameTextBoxUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Eid, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Update_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnameU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameTextBoxUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EpassU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Update_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 115, 29));
        jLabel7.setText("Search: ");

        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(5, 58, 102));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout Mnagae_employeeLayout = new javax.swing.GroupLayout(Mnagae_employee);
        Mnagae_employee.setLayout(Mnagae_employeeLayout);
        Mnagae_employeeLayout.setHorizontalGroup(
            Mnagae_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Mnagae_employeeLayout.createSequentialGroup()
                .addGroup(Mnagae_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Mnagae_employeeLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Mnagae_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Mnagae_employeeLayout.createSequentialGroup()
                            .addGap(321, 321, 321)
                            .addComponent(deleteSelectedEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Mnagae_employeeLayout.createSequentialGroup()
                            .addGap(213, 213, 213)
                            .addGroup(Mnagae_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(Mnagae_employeeLayout.createSequentialGroup()
                            .addGap(86, 86, 86)
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Mnagae_employeeLayout.createSequentialGroup()
                            .addGap(283, 283, 283)
                            .addComponent(jLabel5))
                        .addGroup(Mnagae_employeeLayout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        Mnagae_employeeLayout.setVerticalGroup(
            Mnagae_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Mnagae_employeeLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(Mnagae_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteSelectedEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(Mnagae_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        jTabbedPane1.addTab("Manage Employees", Mnagae_employee);

        The_Main_Panel.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, -40, 840, 920));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(The_Main_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(The_Main_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTabbedPane1.setSelectedIndex(1);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        //Check for valid user name or password:
        
        if(updateUserNameTextBox.getText().isEmpty()||updatePassTextBox.getText().isEmpty()||updateNameTextBox.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a valid username or password.", "Error", JOptionPane.INFORMATION_MESSAGE);
        }else{
            
            
        if(updateUserNameTextBox.getText().equals(currentAdminName.getText())&&updatePassTextBox.getText().equals(currentAdminPass.getText()) &&updateNameTextBox.getText().equals(currentAdminName.getText()))
        {
            JOptionPane.showMessageDialog(this, "Please enter the data you want to update.", "Error", JOptionPane.INFORMATION_MESSAGE);
        }else {
            
            //Data Base code will be here
            try{
                ArrayList<User> adminAccount = UDB.search("id = 1");
                adminAccount.get(0).setName(updateNameTextBox.getText());
                adminAccount.get(0).setPassword(updatePassTextBox.getText());
                adminAccount.get(0).setUserName((String)updateUserNameTextBox.getText());
            }catch(Exception error){
                    System.out.println(error.getLocalizedMessage());
             }
            
            currentAdminPass.setText(updatePassTextBox.getText());
            currentAdminName.setText(updateNameTextBox.getText());
            currentAdminUserName.setText(updateUserNameTextBox.getText());
            
            JOptionPane.showMessageDialog(this, "Update done successfuly.", "Done", JOptionPane.DEFAULT_OPTION);

        }
        }
        
        

        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        

        
        
        jTabbedPane1.setSelectedIndex(2);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1FocusGained

    private void jButton1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1FocusLost

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(new Color(255,115,29));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        // TODO add your handling code here:
        jButton1.setBackground(new Color(250, 171, 120));
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        jButton2.setBackground(new Color(255,115,29));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseMoved
        // TODO add your handling code here:
        jButton2.setBackground(new Color(250, 171, 120));
    }//GEN-LAST:event_jButton2MouseMoved

    private void jButton4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseMoved
        // TODO add your handling code here:
        jButton4.setBackground(new Color(250, 171, 120));
    }//GEN-LAST:event_jButton4MouseMoved

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:
        jButton4.setBackground(new Color(255,115,29));
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
        jButton3.setBackground(new Color(255,115,29));
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseMoved
        // TODO add your handling code here:
        jButton3.setBackground(new Color(250, 171, 120));
    }//GEN-LAST:event_jButton3MouseMoved

    private void deleteSelectedEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSelectedEmployeeActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel tbl1 = (DefaultTableModel) employeeTable.getModel();
        
        if(employeeTable.getSelectedRowCount()==1){
            try{
                DefaultTableModel Etb = (DefaultTableModel) employeeTable.getModel();
                int userId= Integer.parseInt(Etb.getValueAt(employeeTable.getSelectedRow(), 0).toString());
                UDB.delete("id= "+userId);
                tbl1.removeRow(employeeTable.getSelectedRow());
                JOptionPane.showMessageDialog(this, "Employee deleted succussfuly.","Done",JOptionPane.DEFAULT_OPTION);

            }catch(Exception error){
                System.out.println(error.getLocalizedMessage());
            }
        }else{
            
            if(employeeTable.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "There are no employees to delete.!", "Error", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Please select employee to delete.!", "Error", JOptionPane.INFORMATION_MESSAGE);

            }
        }
        
        //Set Update Employee fields = null
        Eid.setText("");
        EnameU.setText("");
        EpassU.setText("");
        userNameTextBoxUpdate.setText("");
        
    }//GEN-LAST:event_deleteSelectedEmployeeActionPerformed

    private void updateUserNameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserNameTextBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_updateUserNameTextBoxActionPerformed

    private void jButton5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseMoved

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        login loginFrame = new login();
        loginFrame.setVisible(true);
        loginFrame.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void updatePassTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePassTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatePassTextBoxActionPerformed

    private void EIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EIdActionPerformed

    private void EidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EidActionPerformed

    private void Add_EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_EmployeeActionPerformed
        // TODO add your handling code here:
        String employeeId=EId.getText();
        int employeeIdInInt=Integer.parseInt(EId.getText());
        String employeeName=Ename.getText();
        String employeeUserName=userNameTextBox.getText();
        String employeePassword=Epass.getText();
        String employeeType=(String) addType.getSelectedItem();
        
        //Check for the fields
        //Check for the unique id from data base ,the code will be here
        
        if(employeeName.isEmpty() || employeePassword.isEmpty() || employeeType.isEmpty() || employeeId.isEmpty())
            JOptionPane.showMessageDialog(this, "This fields cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);

        
        else{
            // Add employee to data base
            try{
                if(isUserNameUnique(employeeUserName) && isUserIdUnique(employeeIdInInt)){ //Check for unique id and username
                    if(employeeType.equals("sales")){
                        SalesEmp newSalesEmp = new SalesEmp(employeeIdInInt,employeeName,employeeUserName,employeePassword,employeeType);
                    }else if(employeeType.equals("inventory")){
                        InventoryEmp newInventoryEmp = new InventoryEmp(employeeIdInInt,employeeName,employeeUserName,employeePassword,employeeType);
                    }else if(employeeType.equals("marketing")){
                        MarketingEmp newMarketingEmp = new MarketingEmp(employeeIdInInt,employeeName,employeeUserName,employeePassword,employeeType);
                    }
                DefaultTableModel Etb = (DefaultTableModel) employeeTable.getModel();
                String data[]={employeeId,employeeName,employeeUserName,employeePassword,(String) addType.getSelectedItem()};
                Etb.addRow(data);
                JOptionPane.showMessageDialog(this, "Employee Added Successfuly", "Done", JOptionPane.DEFAULT_OPTION);
                EId.setText("");
                Ename.setText("");
                Epass.setText("");
                userNameTextBox.setText("");
                }else{
                    JOptionPane.showMessageDialog(this, "Please enter a unique username and password", "Error", JOptionPane.ERROR_MESSAGE);

                }

            }catch(Exception error){
                System.out.println(error.getLocalizedMessage());
            }


        }
    }//GEN-LAST:event_Add_EmployeeActionPerformed

    private void Update_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_employeeActionPerformed
        // TODO add your handling code here:
        int employeeId=Integer.parseInt(Eid.getText());
        String employeeName=EnameU.getText();
        String employeeUserName=userNameTextBoxUpdate.getText();
        String employeePassword=EpassU.getText();
        String employeeType=(String) updateComboBox.getSelectedItem();
        DefaultTableModel Etb = (DefaultTableModel) employeeTable.getModel();
        
        //Check for the fields
        if(employeeName.isEmpty()||employeePassword.isEmpty()||employeeType.isEmpty())
            JOptionPane.showMessageDialog(this, "This fields cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
        else{
            
            if(employeeTable.getSelectedRowCount()==1){
                //Data base code will be here
                try{
                  
                        User employee = UDB.search("id = " + employeeId).get(0);
                        employee.setName(employeeName);
                        employee.setUserName(employeeUserName);
                        employee.setPassword(employeePassword);
                        employee.setType(employeeType);

                    Etb.setValueAt(employeeName,employeeTable.getSelectedRow(), 1);
                    Etb.setValueAt(employeeUserName, employeeTable.getSelectedRow(), 2);
                    Etb.setValueAt(employeePassword,employeeTable.getSelectedRow(), 3);
                    Etb.setValueAt(employeeType,employeeTable.getSelectedRow(), 4);
                    JOptionPane.showMessageDialog(this, "Employee Updated Successfuly", "Done", JOptionPane.DEFAULT_OPTION);

                }catch(Exception  error){
                    System.out.println(error.getLocalizedMessage());
                }

            }else{
                JOptionPane.showMessageDialog(this, "Select one row ro update", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_Update_employeeActionPerformed

    private void employeeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeTableMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel Etb = (DefaultTableModel) employeeTable.getModel();
        
        String id= Etb.getValueAt(employeeTable.getSelectedRow(), 0).toString();
        String name= Etb.getValueAt(employeeTable.getSelectedRow(), 1).toString();
        String userName=Etb.getValueAt(employeeTable.getSelectedRow(), 2).toString();
        String password= Etb.getValueAt(employeeTable.getSelectedRow(), 3).toString();
        String type= Etb.getValueAt(employeeTable.getSelectedRow(), 4).toString();
        
        Eid.setText(id);
        EnameU.setText(name);
        userNameTextBoxUpdate.setText(userName);
        EpassU.setText(password);
        updateComboBox.setSelectedItem(type);

    }//GEN-LAST:event_employeeTableMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        //Search in table
        DefaultTableModel table= (DefaultTableModel) employeeTable.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        employeeTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(jTextField1.getText().trim().toLowerCase()));
       

    }//GEN-LAST:event_jTextField1KeyReleased

    private void userNameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextBoxActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1KeyPressed

    private void updateNameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateNameTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateNameTextBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Employee;
    private javax.swing.JTextField EId;
    private javax.swing.JTextField Eid;
    private javax.swing.JTextField Ename;
    private javax.swing.JTextField EnameU;
    private javax.swing.JTextField Epass;
    private javax.swing.JTextField EpassU;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Manage_admin;
    private javax.swing.JPanel Mnagae_employee;
    private javax.swing.JPanel Side_Bar;
    private javax.swing.JPanel The_Main_Panel;
    private javax.swing.JPanel Update_Account;
    private javax.swing.JButton Update_employee;
    private javax.swing.JComboBox<String> addType;
    private javax.swing.JLabel currentAdminName;
    private javax.swing.JLabel currentAdminNameLabel;
    public javax.swing.JLabel currentAdminPass;
    private javax.swing.JLabel currentAdminPassLabel;
    private javax.swing.JLabel currentAdminUserName;
    private javax.swing.JLabel currentAdminUserNameLabel;
    private javax.swing.JButton deleteSelectedEmployee;
    private javax.swing.JTable employeeTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> updateComboBox;
    private javax.swing.JTextField updateNameTextBox;
    private javax.swing.JTextField updatePassTextBox;
    private javax.swing.JTextField updateUserNameTextBox;
    private javax.swing.JTextField userNameTextBox;
    private javax.swing.JTextField userNameTextBoxUpdate;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
