/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import javax.swing.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import Database.*;
import Product.*;
import javax.swing.table.TableModel;
import java.sql.Date;
/**
 *
 * @author shehab
 */
public class MarketingFrame extends javax.swing.JFrame {

    /**
     * Creates new form MarketingFrame
     */
    public MarketingFrame() {
        initComponents();
        
        //Add current products to Make reports Table
        try{
            
       ArrayList<Product> currentProducts = PDB.search("*");
        DefaultTableModel currentProductsTable = (DefaultTableModel)currentProductsTableInGUI.getModel();
        
        for(int i=0;i<currentProducts.size();i++){
            String offerPrice;
            if(currentProducts.get(i).getOfferPrice()==-1)
                offerPrice="No Offer";
            else
                offerPrice=currentProducts.get(i).getOfferPrice()+"";

            String product[]={
                String.valueOf(currentProducts.get(i).getId()),
                String.valueOf(currentProducts.get(i).getName()),
                String.valueOf(currentProducts.get(i).getPrice()),
                offerPrice,
                String.valueOf(currentProducts.get(i).getEpireDate()),
                String.valueOf(currentProducts.get(i).getType())
            };
            
            currentProductsTable.addRow(product);
        }
        
        }catch(Exception error){
                    System.out.println(error.getLocalizedMessage());
        }
        
        
        
        //Add current products in make offers Table

        try{
            
       ArrayList<Product> currentProducts = PDB.search("*");
        DefaultTableModel currentProductsTable = (DefaultTableModel)currentProductsTableInOffers.getModel();
        
        for(int i=0;i<currentProducts.size();i++){
            String offerPrice;
            if(currentProducts.get(i).getOfferPrice()==-1)
                offerPrice="No Offer";
            else
                offerPrice=currentProducts.get(i).getOfferPrice()+"";

            String product[]={
                String.valueOf(currentProducts.get(i).getId()),
                String.valueOf(currentProducts.get(i).getName()),
                String.valueOf(currentProducts.get(i).getPrice()),
                offerPrice,
                String.valueOf(currentProducts.get(i).getEpireDate()),
                String.valueOf(currentProducts.get(i).getType())
            };
            
            currentProductsTable.addRow(product);
        }
        
        }catch(Exception error){
                    System.out.println(error.getLocalizedMessage());
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        The_Main_Panel = new javax.swing.JPanel();
        Side_Bar = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Manage_Marketing = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        currentPassword = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        currentUserName = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        Update_Account = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        Make_Reports = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        currentProductsTableInGUI = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        priceTo = new javax.swing.JTextField();
        priceFrom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        expireDateFrom = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        expireDateTo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        selectedType = new javax.swing.JComboBox<>();
        Make_Offers = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        currentProductsTableInOffers = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Pid = new javax.swing.JTextField();
        PPrice = new javax.swing.JTextField();
        Pname = new javax.swing.JTextField();
        Add_Employee = new javax.swing.JButton();
        PType = new javax.swing.JComboBox<>();
        POfferPrice = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        PExpireDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Marketing");
        setResizable(false);

        The_Main_Panel.setBackground(java.awt.Color.white);
        The_Main_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Side_Bar.setBackground(new java.awt.Color(255, 241, 226));

        jButton1.setBackground(new java.awt.Color(255, 115, 29));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("Home");
        jButton1.setBorderPainted(false);
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton1FocusLost(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 115, 29));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setText("Manage Account");
        jButton2.setMaximumSize(new java.awt.Dimension(84, 26));
        jButton2.setMinimumSize(new java.awt.Dimension(84, 26));
        jButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton2MouseMoved(evt);
            }
        });
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 115, 29));
        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jButton4.setForeground(java.awt.Color.white);
        jButton4.setText("Make Reports");
        jButton4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton4MouseMoved(evt);
            }
        });
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 115, 29));
        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jButton5.setForeground(java.awt.Color.white);
        jButton5.setText("Logout");
        jButton5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton5MouseMoved(evt);
            }
        });
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 115, 29));
        jButton7.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jButton7.setForeground(java.awt.Color.white);
        jButton7.setText("Make Offers");
        jButton7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton7MouseMoved(evt);
            }
        });
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7MouseExited(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Side_BarLayout = new javax.swing.GroupLayout(Side_Bar);
        Side_Bar.setLayout(Side_BarLayout);
        Side_BarLayout.setHorizontalGroup(
            Side_BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Side_BarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Side_BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Side_BarLayout.createSequentialGroup()
                        .addGroup(Side_BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Side_BarLayout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Side_BarLayout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        Side_BarLayout.setVerticalGroup(
            Side_BarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Side_BarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 451, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        The_Main_Panel.add(Side_Bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 870));

        jTabbedPane1.setBackground(java.awt.Color.white);
        jTabbedPane1.setForeground(new java.awt.Color(5, 58, 102));
        jTabbedPane1.setDoubleBuffered(true);

        Home.setBackground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(5, 58, 102));
        jLabel1.setText("Marketing");

        jPanel4.setBackground(new java.awt.Color(255, 115, 29));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 115, 29));
        jLabel3.setText("Welcome, MarketingName");

        jLabel6.setPreferredSize(new java.awt.Dimension(250, 250));

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addContainerGap(316, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(305, 305, 305))
            .addGroup(HomeLayout.createSequentialGroup()
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel3)
                .addContainerGap(487, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", Home);

        Manage_Marketing.setBackground(java.awt.Color.white);
        Manage_Marketing.setForeground(new java.awt.Color(5, 58, 102));
        Manage_Marketing.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(5, 58, 102));
        jLabel4.setText("Manage Marketing Account");

        currentPassword.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        currentPassword.setForeground(new java.awt.Color(5, 58, 102));
        currentPassword.setText("marketing");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 115, 29));
        jLabel8.setText("Current Password   :");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 115, 29));
        jLabel9.setText("Current User Name :");

        currentUserName.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        currentUserName.setForeground(new java.awt.Color(5, 58, 102));
        currentUserName.setText("marketing");

        jPanel8.setBackground(new java.awt.Color(255, 115, 29));
        jPanel8.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        Update_Account.setBackground(java.awt.Color.white);
        Update_Account.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(5, 58, 102));
        jLabel12.setText("Update Account");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 115, 29));
        jLabel13.setText("User Name: ");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 115, 29));
        jLabel14.setText("Password: ");

        userNameField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        userNameField.setForeground(new java.awt.Color(5, 58, 102));
        userNameField.setText(currentUserName.getText());
        userNameField.setToolTipText("");
        userNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFieldActionPerformed(evt);
            }
        });

        passwordField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        passwordField.setForeground(new java.awt.Color(5, 58, 102));
        passwordField.setToolTipText("");
        passwordField.setText(currentPassword.getText());
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 115, 29));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jButton3.setForeground(java.awt.Color.white);
        jButton3.setText("Update");
        jButton3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton3MouseMoved(evt);
            }
        });
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Update_AccountLayout = new javax.swing.GroupLayout(Update_Account);
        Update_Account.setLayout(Update_AccountLayout);
        Update_AccountLayout.setHorizontalGroup(
            Update_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Update_AccountLayout.createSequentialGroup()
                .addGroup(Update_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Update_AccountLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel12))
                    .addGroup(Update_AccountLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(Update_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(60, 60, 60)
                        .addGroup(Update_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(passwordField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Update_AccountLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        Update_AccountLayout.setVerticalGroup(
            Update_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Update_AccountLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addGap(64, 64, 64)
                .addGroup(Update_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(Update_AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout Manage_MarketingLayout = new javax.swing.GroupLayout(Manage_Marketing);
        Manage_Marketing.setLayout(Manage_MarketingLayout);
        Manage_MarketingLayout.setHorizontalGroup(
            Manage_MarketingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Manage_MarketingLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(Manage_MarketingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Update_Account, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Manage_MarketingLayout.createSequentialGroup()
                        .addGroup(Manage_MarketingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Manage_MarketingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Manage_MarketingLayout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addGroup(Manage_MarketingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Manage_MarketingLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140))
        );
        Manage_MarketingLayout.setVerticalGroup(
            Manage_MarketingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Manage_MarketingLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(Manage_MarketingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(Manage_MarketingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(Update_Account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage Marketing Account", Manage_Marketing);

        Make_Reports.setBackground(java.awt.Color.white);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 115, 29));
        jLabel5.setText("Price:");

        jPanel7.setBackground(new java.awt.Color(255, 115, 29));
        jPanel7.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(5, 58, 102));
        jLabel11.setText("Make Reports");

        currentProductsTableInGUI.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        currentProductsTableInGUI.setForeground(new java.awt.Color(5, 58, 102));
        currentProductsTableInGUI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Price", "Offer Price", "Expire Date", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        currentProductsTableInGUI.setAutoscrolls(false);
        currentProductsTableInGUI.setGridColor(new java.awt.Color(255, 241, 226));
        currentProductsTableInGUI.setRequestFocusEnabled(false);
        currentProductsTableInGUI.setSelectionBackground(new java.awt.Color(255, 241, 226));
        currentProductsTableInGUI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                currentProductsTableInGUIMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(currentProductsTableInGUI);
        if (currentProductsTableInGUI.getColumnModel().getColumnCount() > 0) {
            currentProductsTableInGUI.getColumnModel().getColumn(0).setResizable(false);
            currentProductsTableInGUI.getColumnModel().getColumn(1).setResizable(false);
            currentProductsTableInGUI.getColumnModel().getColumn(2).setResizable(false);
            currentProductsTableInGUI.getColumnModel().getColumn(3).setResizable(false);
            currentProductsTableInGUI.getColumnModel().getColumn(4).setResizable(false);
            currentProductsTableInGUI.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 115, 29));
        jLabel7.setText("Search: ");

        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(5, 58, 102));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 115, 29));
        jButton6.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jButton6.setForeground(java.awt.Color.white);
        jButton6.setText("Filter");
        jButton6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton6MouseMoved(evt);
            }
        });
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 115, 29));
        jLabel10.setText("Type:");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 115, 29));
        jLabel16.setText("Current Products");

        priceTo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        priceFrom.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        priceFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceFromActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(5, 58, 102));
        jLabel2.setText("From:");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(5, 58, 102));
        jLabel15.setText("To:");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(5, 58, 102));
        jLabel17.setText("From:");

        expireDateFrom.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        expireDateFrom.setForeground(new java.awt.Color(204, 204, 204));
        expireDateFrom.setText("yyyy,mm,dd");
        expireDateFrom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                expireDateFromFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                expireDateFromFocusLost(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(5, 58, 102));
        jLabel18.setText("To:");

        expireDateTo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        expireDateTo.setForeground(new java.awt.Color(204, 204, 204));
        expireDateTo.setText("yyyy,mm,dd");
        expireDateTo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                expireDateToFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                expireDateToFocusLost(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 115, 29));
        jLabel20.setText("Expire Date:");

        selectedType.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        selectedType.setForeground(new java.awt.Color(5, 58, 102));
        selectedType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "all", "normal", "damaged", "returned" }));
        selectedType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Make_ReportsLayout = new javax.swing.GroupLayout(Make_Reports);
        Make_Reports.setLayout(Make_ReportsLayout);
        Make_ReportsLayout.setHorizontalGroup(
            Make_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Make_ReportsLayout.createSequentialGroup()
                .addGroup(Make_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Make_ReportsLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel11))
                    .addGroup(Make_ReportsLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Make_ReportsLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Make_ReportsLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Make_ReportsLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(Make_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Make_ReportsLayout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addComponent(jLabel16))))
                    .addGroup(Make_ReportsLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(Make_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addGroup(Make_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Make_ReportsLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(Make_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel2))
                                .addGroup(Make_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Make_ReportsLayout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(priceFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Make_ReportsLayout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(expireDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Make_ReportsLayout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(selectedType, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(77, 77, 77)
                        .addGroup(Make_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Make_ReportsLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(expireDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Make_ReportsLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(41, 41, 41)
                                .addComponent(priceTo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(Make_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Make_ReportsLayout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(jLabel20)
                    .addContainerGap(662, Short.MAX_VALUE)))
        );
        Make_ReportsLayout.setVerticalGroup(
            Make_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Make_ReportsLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(Make_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Make_ReportsLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(6, 6, 6)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(Make_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addComponent(jLabel16)
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addGroup(Make_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(priceFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(28, 28, 28)
                        .addGroup(Make_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(expireDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)))
                    .addGroup(Make_ReportsLayout.createSequentialGroup()
                        .addComponent(priceTo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(expireDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(Make_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(selectedType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Make_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Make_ReportsLayout.createSequentialGroup()
                    .addContainerGap(656, Short.MAX_VALUE)
                    .addComponent(jLabel20)
                    .addGap(207, 207, 207)))
        );

        jTabbedPane1.addTab("Make Reports", Make_Reports);

        jPanel2.setBackground(java.awt.Color.white);

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(5, 58, 102));
        jLabel19.setText("Make Offers");

        jPanel9.setBackground(new java.awt.Color(255, 115, 29));
        jPanel9.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        currentProductsTableInOffers.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        currentProductsTableInOffers.setForeground(new java.awt.Color(5, 58, 102));
        currentProductsTableInOffers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Price", "Offer Price", "Expire Date", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        currentProductsTableInOffers.setAutoscrolls(false);
        currentProductsTableInOffers.setGridColor(java.awt.Color.white);
        currentProductsTableInOffers.setRequestFocusEnabled(false);
        currentProductsTableInOffers.setSelectionBackground(new java.awt.Color(255, 241, 226));
        currentProductsTableInOffers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                currentProductsTableInOffersMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(currentProductsTableInOffers);
        if (currentProductsTableInOffers.getColumnModel().getColumnCount() > 0) {
            currentProductsTableInOffers.getColumnModel().getColumn(0).setResizable(false);
            currentProductsTableInOffers.getColumnModel().getColumn(1).setResizable(false);
            currentProductsTableInOffers.getColumnModel().getColumn(2).setResizable(false);
            currentProductsTableInOffers.getColumnModel().getColumn(3).setResizable(false);
            currentProductsTableInOffers.getColumnModel().getColumn(4).setResizable(false);
            currentProductsTableInOffers.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 115, 29));
        jLabel22.setText("Current Products");

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(5, 58, 102));
        jLabel21.setText("Product Info");

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 115, 29));
        jLabel23.setText("Id:");

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 115, 29));
        jLabel24.setText("Price:");

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 115, 29));
        jLabel25.setText("Name:");

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 115, 29));
        jLabel26.setText("Type:");

        Pid.setEditable(false);
        Pid.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Pid.setForeground(new java.awt.Color(5, 58, 102));
        Pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PidActionPerformed(evt);
            }
        });

        PPrice.setEditable(false);
        PPrice.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        PPrice.setForeground(new java.awt.Color(5, 58, 102));

        Pname.setEditable(false);
        Pname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Pname.setForeground(new java.awt.Color(5, 58, 102));

        Add_Employee.setBackground(new java.awt.Color(255, 115, 29));
        Add_Employee.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        Add_Employee.setForeground(java.awt.Color.white);
        Add_Employee.setText("Make Offer");
        Add_Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_EmployeeActionPerformed(evt);
            }
        });

        PType.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        PType.setForeground(new java.awt.Color(5, 58, 102));
        PType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "normal", "returned", "damaged" }));
        PType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTypeActionPerformed(evt);
            }
        });

        POfferPrice.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        POfferPrice.setForeground(new java.awt.Color(5, 58, 102));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 115, 29));
        jLabel27.setText("Offer Price:");

        jLabel28.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 115, 29));
        jLabel28.setText("Expire Date:");

        PExpireDate.setEditable(false);
        PExpireDate.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        PExpireDate.setForeground(new java.awt.Color(5, 58, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Pid, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Pname, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel24)
                                        .addComponent(jLabel26))
                                    .addGap(102, 102, 102)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PPrice)
                                        .addComponent(PType, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PExpireDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(POfferPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(Add_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel21)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel21)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(POfferPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PExpireDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Add_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(262, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel22)))
                .addGap(62, 62, 62))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Make_OffersLayout = new javax.swing.GroupLayout(Make_Offers);
        Make_Offers.setLayout(Make_OffersLayout);
        Make_OffersLayout.setHorizontalGroup(
            Make_OffersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Make_OffersLayout.setVerticalGroup(
            Make_OffersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Make Offers", Make_Offers);

        The_Main_Panel.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, -40, 850, 920));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(The_Main_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(The_Main_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        // TODO add your handling code here:
        jButton1.setBackground(new Color(250, 171, 120));
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1FocusGained

    private void jButton1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1FocusLost

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(new Color(255,115,29));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseMoved
        // TODO add your handling code here:
        jButton4.setBackground(new Color(250, 171, 120));
    }//GEN-LAST:event_jButton4MouseMoved

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:
        jButton4.setBackground(new Color(255,115,29));
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        currentProductsTableInGUI.setModel(new DefaultTableModel(null,new String[]{"Id","Name","Price","Offer Price","Expire Date","Type"}));
        try{
            
       ArrayList<Product> currentProducts = PDB.search("*");
        DefaultTableModel currentProductsTable = (DefaultTableModel)currentProductsTableInGUI.getModel();
        
        for(int i=0;i<currentProducts.size();i++){
            String offerPrice;
            if(currentProducts.get(i).getOfferPrice()==-1)
                offerPrice="No Offer";
            else
                offerPrice=currentProducts.get(i).getOfferPrice()+"";

            String product[]={
                String.valueOf(currentProducts.get(i).getId()),
                String.valueOf(currentProducts.get(i).getName()),
                String.valueOf(currentProducts.get(i).getPrice()),
                offerPrice,
                String.valueOf(currentProducts.get(i).getEpireDate()),
                String.valueOf(currentProducts.get(i).getType())
            };
            
            currentProductsTable.addRow(product);
        }
        
        }catch(Exception error){
                    System.out.println(error.getLocalizedMessage());
        }
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseMoved
        // TODO add your handling code here:
        jButton5.setBackground(new Color(250, 171, 120));

    }//GEN-LAST:event_jButton5MouseMoved

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        // TODO add your handling code here:
                jButton5.setBackground(new Color(255,115,29));

    }//GEN-LAST:event_jButton5MouseExited

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        login loginFrame = new login();
        loginFrame.setVisible(true);
        loginFrame.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        //Check for valid user name or password:

        if(userNameField.getText().isEmpty()||passwordField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a valid username or password.", "Error", JOptionPane.INFORMATION_MESSAGE);
        }else{

            if(userNameField.getText().equals(currentUserName.getText())&&passwordField.getText().equals(currentPassword.getText()))
            {
                JOptionPane.showMessageDialog(this, "Please enter the new Username or Password you want update.", "Error", JOptionPane.INFORMATION_MESSAGE);
            } else if(userNameField.getText().equals(currentUserName.getText())&& !passwordField.getText().equals(currentPassword.getText())){
                //Data Base code will be here
                currentPassword.setText(passwordField.getText());
                JOptionPane.showMessageDialog(this, "Update done successfuly.", "Done", JOptionPane.DEFAULT_OPTION);
            } else if(passwordField.getText().equals(currentPassword.getText())&& !userNameField.getText().equals(currentUserName.getText())){
                //Data Base code will be here
                currentUserName.setText(userNameField.getText());
                JOptionPane.showMessageDialog(this, "Update done successfuly.", "Done", JOptionPane.DEFAULT_OPTION);

            }else {
                //Data Base code will be here
                currentPassword.setText(passwordField.getText());

                //Data Base code will be here
                currentUserName.setText(userNameField.getText());
                JOptionPane.showMessageDialog(this, "Update done successfuly.", "Done", JOptionPane.DEFAULT_OPTION);

            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
        jButton3.setBackground(new Color(255,115,29));
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseMoved
        // TODO add your handling code here:
        jButton3.setBackground(new Color(250, 171, 120));
    }//GEN-LAST:event_jButton3MouseMoved

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        jButton2.setBackground(new Color(255,115,29));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseMoved
        // TODO add your handling code here:
        jButton2.setBackground(new Color(250, 171, 120));
    }//GEN-LAST:event_jButton2MouseMoved

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:



        double priceFromInDouble = 0;
        double priceToInDouble= 1000000000;
        Date dateFrom = Date.valueOf("1970-1-1");
        Date dateTo = Date.valueOf("2500-1-1");
        String productsType = (String)selectedType.getSelectedItem();
        
        try{
                //Get values from text box
            if(!priceFrom.getText().isEmpty())
                priceFromInDouble= Double.parseDouble(priceFrom.getText());
            if(!priceTo.getText().isEmpty())
                priceToInDouble= Double.parseDouble(priceTo.getText());
            if(!expireDateFrom.getText().equals("yyyy,mm,dd"))
                dateFrom = Date.valueOf(expireDateFrom.getText());
            if(!expireDateTo.getText().equals("yyyy,mm,dd"))
                dateTo = Date.valueOf(expireDateTo.getText());
            
            
            //Get productts from data base and set its to the table
            //there will be condition here to get the right products type
            ArrayList<Product> products;
            if(productsType.equals("all") )
               products = PDB.search("price between "+priceFromInDouble+" and "+priceToInDouble+" and expiredate between "+"'"+dateFrom+"'"+" and "+"'"+dateTo+"'");
            else  
               products = PDB.search("price between "+priceFromInDouble+" and "+priceToInDouble+" and type = "+"'"+productsType+"'"+" and expiredate between "+"'"+dateFrom+"'"+" and "+"'"+dateTo+"'");
            
        currentProductsTableInGUI.setModel(new DefaultTableModel(null,new String[]{"Id","Name","Price","Offer Price","Expire Date","Type"}));
            DefaultTableModel tableModel = (DefaultTableModel) currentProductsTableInGUI.getModel();
        for(int i=0;i<products.size();i++){
            String offerPrice =products.get(i).getOfferPrice()+"";
            if(products.get(i).getOfferPrice() == -1)
                offerPrice = "No Offer";
            
            String product[] = {
                products.get(i).getId()+"",
                products.get(i).getName(),
                products.get(i).getPrice()+"",
                offerPrice,
                products.get(i).getEpireDate()+"",
                products.get(i).getType()
            };
            tableModel.addRow(product);
            
        }
        
        }catch(Exception error){
                    System.out.println(error.getLocalizedMessage());
        }
        
        //To clear all content of table
//        currentProductsTableInGUI.setModel(new DefaultTableModel(null,new String[]{"Id","Name","Price","Offer Price","Expire Date","Type"}));

            
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseExited

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseMoved

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:

        DefaultTableModel table= (DefaultTableModel) currentProductsTableInGUI.getModel();

        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        currentProductsTableInGUI.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(jTextField1.getText().trim().toLowerCase()));
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void currentProductsTableInGUIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currentProductsTableInGUIMouseClicked
        // TODO add your handling code here:

        DefaultTableModel Etb = (DefaultTableModel) currentProductsTableInGUI.getModel();

        String id= Etb.getValueAt(currentProductsTableInGUI.getSelectedRow(), 0).toString();
        String name= Etb.getValueAt(currentProductsTableInGUI.getSelectedRow(), 1).toString();
        String password= Etb.getValueAt(currentProductsTableInGUI.getSelectedRow(), 2).toString();
        String type= Etb.getValueAt(currentProductsTableInGUI.getSelectedRow(), 3).toString();

    }//GEN-LAST:event_currentProductsTableInGUIMouseClicked

    private void jButton7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseMoved
        // TODO add your handling code here:
                jButton7.setBackground(new Color(250, 171, 120));

    }//GEN-LAST:event_jButton7MouseMoved

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseExited
        // TODO add your handling code here:
                jButton7.setBackground(new Color(255,115,29));

    }//GEN-LAST:event_jButton7MouseExited

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void currentProductsTableInOffersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currentProductsTableInOffersMouseClicked
        // TODO add your handling code here:
        DefaultTableModel Etb = (DefaultTableModel) currentProductsTableInOffers.getModel();
        
        String id= Etb.getValueAt(currentProductsTableInOffers.getSelectedRow(), 0).toString();
        String name= Etb.getValueAt(currentProductsTableInOffers.getSelectedRow(), 1).toString();
        String price= Etb.getValueAt(currentProductsTableInOffers.getSelectedRow(), 2).toString();
        String offerPrice= Etb.getValueAt(currentProductsTableInOffers.getSelectedRow(), 3).toString();
        String expireDate= Etb.getValueAt(currentProductsTableInOffers.getSelectedRow(), 4).toString();
        String type= Etb.getValueAt(currentProductsTableInOffers.getSelectedRow(), 5).toString();

        Pid.setText(id);
        Pname.setText(name);
        PPrice.setText(price);
        if(offerPrice.equals("no offer"))
            POfferPrice.setText("No Offer");
        else
            POfferPrice.setText(offerPrice);
        
        PExpireDate.setText(expireDate);
        PType.setSelectedItem(type);
    }//GEN-LAST:event_currentProductsTableInOffersMouseClicked

    private void PidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PidActionPerformed

    private void Add_EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_EmployeeActionPerformed
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel) currentProductsTableInOffers.getModel();
        int productId = Integer.parseInt(Pid.getText());
        double offerPriceInDouble = Double.parseDouble((String)POfferPrice.getText());
        double price = Double.parseDouble ((String) currentProductsTableInOffers.getValueAt(currentProductsTableInOffers.getSelectedRow(), 2) );
        String offerPriceInString = (String)currentProductsTableInOffers.getValueAt(currentProductsTableInOffers.getSelectedRow(), 2);
        
        if(offerPriceInDouble > price){
            JOptionPane.showMessageDialog(this, "Offer price cannot be bigger than the price", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            if(offerPriceInDouble==0){
                currentProductsTableInOffers.setValueAt("No Offer", currentProductsTableInOffers.getSelectedRow(), 3);
                try{
                    ArrayList<Product> product = PDB.search("id = "+productId);
                    product.get(0).setOfferPrice(-1);
                }catch(Exception error){
                    System.out.println(error.getLocalizedMessage());
                }
                     
            }else{
                try{
                    ArrayList<Product> product = PDB.search("id = "+productId);
                    product.get(0).setOfferPrice(offerPriceInDouble);
                }catch(Exception error){
                    System.out.println(error.getLocalizedMessage());
                }
                currentProductsTableInOffers.setValueAt(POfferPrice.getText(), currentProductsTableInOffers.getSelectedRow(), 3);
            }
            JOptionPane.showMessageDialog(this, "Offer added successfully", "Done", JOptionPane.DEFAULT_OPTION);
        
        }
        
        
        
        
    }//GEN-LAST:event_Add_EmployeeActionPerformed

    private void PTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PTypeActionPerformed

    private void priceFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFromActionPerformed

    private void expireDateFromFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expireDateFromFocusGained
        // TODO add your handling code here:
         if(expireDateFrom.getText().trim().equals("yyyy,mm,dd")){
            expireDateFrom.setText("");
        }
        expireDateFrom.setForeground(new Color(5,58,102));
    }//GEN-LAST:event_expireDateFromFocusGained

    private void expireDateToFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expireDateToFocusLost
        // TODO add your handling code here:
        if(expireDateTo.getText().trim().equals("")){
            expireDateTo.setText("yyyy,mm,dd");
        }
       
    }//GEN-LAST:event_expireDateToFocusLost

    private void expireDateFromFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expireDateFromFocusLost
        // TODO add your handling code here:
        if(expireDateFrom.getText().trim().equals("")){
            expireDateFrom.setText("yyyy,mm,dd");
        }
    }//GEN-LAST:event_expireDateFromFocusLost

    private void expireDateToFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expireDateToFocusGained
        // TODO add your handling code here: expireDateTo
        if(expireDateTo.getText().trim().equals("yyyy,mm,dd")){
            expireDateTo.setText("");
        }
        expireDateTo.setForeground(new Color(5,58,102));
    }//GEN-LAST:event_expireDateToFocusGained

    private void selectedTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarketingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarketingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarketingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarketingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarketingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Employee;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Make_Offers;
    private javax.swing.JPanel Make_Reports;
    private javax.swing.JPanel Manage_Marketing;
    private javax.swing.JTextField PExpireDate;
    private javax.swing.JTextField POfferPrice;
    private javax.swing.JTextField PPrice;
    private javax.swing.JComboBox<String> PType;
    private javax.swing.JTextField Pid;
    private javax.swing.JTextField Pname;
    private javax.swing.JPanel Side_Bar;
    private javax.swing.JPanel The_Main_Panel;
    private javax.swing.JPanel Update_Account;
    public javax.swing.JLabel currentPassword;
    private javax.swing.JTable currentProductsTableInGUI;
    private javax.swing.JTable currentProductsTableInOffers;
    private javax.swing.JLabel currentUserName;
    private javax.swing.JTextField expireDateFrom;
    private javax.swing.JTextField expireDateTo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField passwordField;
    private javax.swing.JTextField priceFrom;
    private javax.swing.JTextField priceTo;
    private javax.swing.JComboBox<String> selectedType;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables

    private TableModel DefaultTableModel(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
